server:
  port: ${SERVER_PORT}
  error:
    include-stacktrace: always

security:
  jwt:
    public-key: classpath:jwt_public_key.der

pdf:
  template-path: /templates
  resource-path: ${pdf.template-path}/resources

spring:
  application:
    name: pdf-service

logging:
  level:
    web:
      DEBUG